name: Build Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -la

      - name: Build Successful
        run: echo "Project Build Completed Successfully!"
